definitions:
  models.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: API for Meta-Clone
  title: Meta-Clone
  version: "1.0"
paths:
  /communities:
    get:
      operationId: get-communities
      responses:
        "200":
          description: 'status": "success", data: { "communities": []models.Community
            }, "code": 200}'
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get Communities
  /posts:
    get:
      operationId: get-posts
      responses:
        "200":
          description: 'status": "success", data: { "posts": []models.Post }, "code":
            200}'
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get Posts
  /sign-in:
    post:
      operationId: sign-in
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      responses:
        "200":
          description: 'status": "success", "token": string, "code": 200}'
          schema:
            type: string
      summary: Sign In
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
