definitions:
  models.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
paths:
  /sign-in/:
    post:
      operationId: sign-in
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      responses:
        "200":
          description: 'status": "success", "token": string, "code": 200}'
          schema:
            type: string
      summary: Sign In
swagger: "2.0"
