service: messenger-clone
frameworkVersion: "3"

provider:
  environment:
    DSN: ${env:DSN}
    APIG_ENDPOINT:
      Fn::Join:
        - ""
        - - https://
          - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:provider.stage}
  websocketsApiName: websockets-api
  websocketsApiRouteSelectionExpression: $request.body.action
  name: aws
  stage: dev
  runtime: go1.x
  region: ap-southeast-1
  versionFunctions: false

functions:
  api:
    timeout: 30
    handler: bin/api
    package:
      artifact: bin/api.zip
    events:
      - http:
          path: "/{proxy+}"
          method: any
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  ws: 
    handler: bin/ws
    package:
      artifact: bin/ws.zip
    events:
      - websocket:
          route: $default

package:
  individually: true
