name: DEPLOY API

on:
  push:
    branches: [master]
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
jobs:
  Deploy:
    env: 
      DSN: ${{ secrets.DSN }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [21]
        go-version: [1.21.4]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install serverless global
        run: pnpm install -g serverless@latest
      - name: Setup go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Copy file env to api
        run: cd apps/api && ln -s ../../.env .env
      - name: Deploy
        run: cd apps/api && make deploy
      
